# Git stuff
if [ -f ~/.git-completion.bash ]; then
    source ~/.git-completion.bash
fi
if [ -f ~/.git-prompt.sh ]; then
    source ~/.git-prompt.sh
fi

alias git="hub"

# General stuff
#export CLICOLOR=true
#export LSCOLORS=ExFxCxDxBxegedabagacad
export GREP_OPTIONS='--color=auto'

alias ls="ls -Gp -F"

PS1='\e[0;33m[\@] [\u] \W$(__git_ps1 " (%s)") >>> \e[m'

# These are my personal .bashrc and .bash_profile files, add a dot at
# the beggining of the file name, and place it in your home folder,
# if you want to use these settings of course.
