if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

export PATH="/usr/local/mysql/bin:$PATH"

# These are my personal .bashrc and .bash_profile files, add a dot at
# the beggining of the file name, and place it in your home folder,
# if you want to use these settings of course.
